version: '3.7'

services:
  web:
    container_name: deno-giphy
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - db

  db:
    container_name: mongo
    image: mongo:4.2
    ports:
      - 27017:27017